FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Este script espera a que MySQL esté listo
COPY wait_for_db.py .

EXPOSE 5000
